/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProductListCard {
        "code": string;
        "description": string;
        "image": string;
        "name": string;
        "oldPrice": number;
        "points": number;
        "price": number;
        "unitsInPack": number;
    }
}
declare global {
    interface HTMLProductListCardElement extends Components.ProductListCard, HTMLStencilElement {
    }
    var HTMLProductListCardElement: {
        prototype: HTMLProductListCardElement;
        new (): HTMLProductListCardElement;
    };
    interface HTMLElementTagNameMap {
        "product-list-card": HTMLProductListCardElement;
    }
}
declare namespace LocalJSX {
    interface ProductListCard {
        "code"?: string;
        "description"?: string;
        "image"?: string;
        "name"?: string;
        "oldPrice"?: number;
        "points"?: number;
        "price"?: number;
        "unitsInPack"?: number;
    }
    interface IntrinsicElements {
        "product-list-card": ProductListCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "product-list-card": LocalJSX.ProductListCard & JSXBase.HTMLAttributes<HTMLProductListCardElement>;
        }
    }
}
