/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProductCard {
        "code": string;
        "description": string;
        "image": string;
        "name": string;
        "oldPrice": number;
        "points": number;
        "price": number;
        "unitsInPack": number;
    }
}
declare global {
    interface HTMLProductCardElement extends Components.ProductCard, HTMLStencilElement {
    }
    var HTMLProductCardElement: {
        prototype: HTMLProductCardElement;
        new (): HTMLProductCardElement;
    };
    interface HTMLElementTagNameMap {
        "product-card": HTMLProductCardElement;
    }
}
declare namespace LocalJSX {
    interface ProductCard {
        "code"?: string;
        "description"?: string;
        "image"?: string;
        "name"?: string;
        "oldPrice"?: number;
        "points"?: number;
        "price"?: number;
        "unitsInPack"?: number;
    }
    interface IntrinsicElements {
        "product-card": ProductCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "product-card": LocalJSX.ProductCard & JSXBase.HTMLAttributes<HTMLProductCardElement>;
        }
    }
}
